inherit_from: "configs/rgbd/scannet/base_config.yaml"

Dataset:
  dataset_path: "datasets/scannet/scene0696_02"
  Calibration:
    fx: 1169.621094
    fy: 1167.105103
    cx: 646.295044
    cy: 489.927032
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    distorted: False
    width: 1296
    height: 968
    depth_scale: 1000.0